version: '3'
services:
  authentication:
    build: ./authentication
    volumes:
      - ./authentication:/usr/src/authentication
    networks:
      - my-network
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    env_file: ./authentication/.env

  products:
    build: ./products
    volumes:
      - ./products:/usr/src/products
    networks:
      - my-network
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    env_file: ./products/.env

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    networks:
      - my-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '7777:8080'
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
