openapi: 3.0.0
info:
  title: Products
  version: 1.0.0
paths:
  /products:
    get:
      deprecated: false
      description: Fetches all products in the catalog.
    post:
      deprecated: false
      description: Create a new product in the catalog.
