openapi: 3.0.0
info:
  title: Products
  version: 1.0.0
paths:
  /products:
    get:
      deprecated: false
      description: Fetches all products in the catalog.
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
    post:
      deprecated: false
      description: Create a new product in the catalog.
      responses:
        '201':
          description: product created
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              items:
                $ref: '#/components/schemas/product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        manufacturer:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int32
        width:
          type: float
          format: float32
        height:
          type: float
          format: float32
        depth:
          type: float
          format: float32
        barcode:
          type: integer
          format: int64
      required:
        - id
        - title
        - manufacturer
        - price
        - barcode
